import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import compression from 'compression';
import cookieParser from 'cookie-parser';
import { rateLimit } from 'express-rate-limit';
import { resolve } from 'node:path';
import { existsSync } from 'node:fs';
import { auth } from './core.js';
import { authRouter } from './auth-routes.js';
import { workspace } from './workspace-routes.js';
import { attempts } from './attempt-routes.js';
import { payments, webhook } from './payment-routes.js';
import { certificates, verifyCertificate } from './certificate-routes.js';
export const app=express();
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:{directives:{'img-src':["'self'",'data:','https:'],'style-src':["'self'","'unsafe-inline'"],'script-src':["'self'"], 'connect-src':["'self'"]}}}));
app.use(cors({origin:process.env.APP_URL||'http://localhost:5173',credentials:true}));
app.use(compression());
app.use('/api',rateLimit({windowMs:60000,limit:300,standardHeaders:'draft-7',legacyHeaders:false}));
app.post('/api/payments/webhook',express.raw({type:'application/json',limit:'1mb'}),webhook);
app.use(express.json({limit:'1mb'}));app.use(cookieParser());
app.use('/api',(req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.headers.origin&&req.headers.origin!==(process.env.APP_URL||'http://localhost:5173'))return res.status(403).json({message:'Origin is not allowed.'});next();});
app.get('/api/health',(req,res)=>res.json({status:'ok'}));
app.use('/api/auth',authRouter);
app.get('/api/public/certificates/:code',verifyCertificate);
app.use('/api',auth,workspace,attempts,payments,certificates);
app.use('/api',(req,res)=>res.status(404).json({message:'Endpoint not found.'}));
const client=resolve('../client/dist');
if(existsSync(client)){app.use(express.static(client));app.get('/{*path}',(req,res)=>res.sendFile(resolve(client,'index.html')));}
app.use((error,req,res,next)=>{
  if(res.headersSent)return next(error);
  if(error.name==='ZodError')return res.status(400).json({message:error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')});
  if(error.code==='P2002')return res.status(409).json({message:'This record already exists. Refresh and try again.'});
  if(error.code==='P2025')return res.status(404).json({message:'Record not found.'});
  if(error.type==='entity.parse.failed')return res.status(400).json({message:'Invalid JSON.'});
  if(!error.status)console.error(error);
  res.status(error.status||500).json({message:error.status?error.message:'Something went wrong. Please try again.'});
});
